version: "3"

services:
  webserver:
    build:
      context: .
      dockerfile: "./docker/services/php74/Dockerfile"
    container_name: "heroes-php74"
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links:
      - database
    volumes:
      - ./:/var/www/html
      - ./docker/vhosts:/etc/apache2/sites-enabled

  composer:
    image: library/composer:latest
    container_name: "heroes-composer"
    restart: 'no'
    command: 'install --ignore-platform-reqs'
    volumes:
      - ./:/app

  database:
    build:
      context: "./docker/services/postgres"
    container_name: 'heroes-postgres'
    restart: 'always'
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: 'secure_heroes'
      POSTGRES_USER: 'etudiant'
      POSTGRES_PASSWORD: 'Etudiant1'