version: "3"

services:
  webserver:
    build:
      context: "./docker/services/php74"
    container_name: "php74"
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    links:
      - database
    volumes:
      - ./:/var/www/html
      - ./docker/vhosts:/etc/apache2/sites-enabled

  database:
    build:
      context: "./docker/services/postgres"
    container_name: 'postgres'
    restart: 'always'
    ports:
      - "127.0.0.1:${HOST_MACHINE_POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}